### ISSUE TITLE
Compatibility with Symfony 3

### ISSUE THREAD

**Issue by nyroDev** [egeloen/IvoryOrderedFormBundle#12]
Did you intend to update your bundle for Symfony3?
Maybe the only requirements is to update the composer.json.
I din't test it yet, but you may be more quick for that

**Comment by egeloen** [comment]
Yes, the plan is to make it compatible with Symfony3. Not sure what is required... i will give it a try this we.

**Comment by apfelbox** [comment]
First thing is that the `alias` attribute is now deprecated:

https://github.com/egeloen/IvoryOrderedFormBundle/blob/d573184082cb8dee777718cd23bdc552825bf0b0/Resources/config/services.xml#L20

![screen shot 2015-12-04 at 18 08 31](https://cloud.githubusercontent.com/assets/1032411/11595882/0bcbb508-9ab2-11e5-8d6f-6e0e103553a0.png)

https://github.com/symfony/symfony/blob/5615b92cd452cd54f1433a3f53de87c096a1107f/UPGRADE-2.8.md#form

I am currently using this extension in 2.8 and will look out for other deprecations.

**Comment by egeloen** [comment]
I have give a try and its more complicated than what I though. The issue is the library behind this bundle only have a deps on the symfony form component which does not ship the `Kernel` class where the `VERSION` const is available. So making the code compatible is more complex without this base constant and require to find methods which have been added/removed when the deprecattion has been added and then, check about them to make the code compat...

**Comment by nyroDev** [comment]
Maybe the orderFormBundle should ship it's own class and not depend your orderedForm?
Thanks anyway for looking at it

**Comment by egeloen** [comment]
What do you mean by "ship it's own class" ? Removing the lib and put everything in the bundle? It will indeed simplify things but I would prefer keep the bundle/lib decoupled :)

**Comment by nyroDev** [comment]
Yes that's what I meant. It would be like having 2 projects doing very similar things.... (chiwh is not best)

Or maybe an other solution might be to have 2 branches on both project.
One for Symfony 2.*, and an other for 3.*, and handle it via composer versions requirements.

This way you would know the symfony version and don't rely on Version on Kernel as you mentionned, right?

**Comment by nyroDev** [comment]
Thanks for your quick update!
